server:
  port: 80
spring:
  application:
    name: cloud-order-01
eureka:
  client:
    register-with-eureka: true #是否将自己注册进注册中心
    fetch-registry: true
    serviceUrl:
        defaultZone: http://localhost:8964/eureka
